language: r

r_github_packages:
- jimhester/robustr
- jimhester/covr

after_success:
- Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: Ys9Sr8xRsm1zql8AhVcEX5vBbajmGyZyVRs/faOArktV1u1zy112M5bGvbeCuOAWEifpwhUppATXrndRf0EqwnwTEsrbriAVlY5Gijmx4D+JoTfb/T+PJ5TwX5n3d8Xe5egqf0CAL9JIeR3SfpXmkPPAsszeaR5lSQcggJuji+M=
