language: r
sudo: false
cache: packages
dist: trusty
warnings_are_errors: false

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel

r_binary_packages:
- covr

r_check_args: "--as-cran"

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: Ys9Sr8xRsm1zql8AhVcEX5vBbajmGyZyVRs/faOArktV1u1zy112M5bGvbeCuOAWEifpwhUppATXrndRf0EqwnwTEsrbriAVlY5Gijmx4D+JoTfb/T+PJ5TwX5n3d8Xe5egqf0CAL9JIeR3SfpXmkPPAsszeaR5lSQcggJuji+M=
